name = "cillnet" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
routes = [
  { pattern = "cillnet.my.id", custom_domain = true },
  { pattern = "ava.game.naver.com.cillnet.my.id", custom_domain = true },
  { pattern = "graph.instagram.com.cillnet.my.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.cillnet.my.id", custom_domain = true },
  { pattern = "investors.spotify.com.cillnet.my.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.cillnet.my.id", custom_domain = true },
  { pattern = "cache.netflix.com.cillnet.my.id", custom_domain = true },
  { pattern = "blog.webex.com.cillnet.my.id", custom_domain = true },
  { pattern = "support.zoom.us.cillnet.my.id", custom_domain = true },
]

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "a0c9753e-7ef9-4e34-a9df-3e65c8eb2efd"
